// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rigmjjvokqrsrhfeyyul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZ21qanZva3Fyc3JoZmV5eXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNDY0MzAsImV4cCI6MjA3NTYyMjQzMH0.QqrjxVZZQPk_JKOYYei7PXHv92bfu52PGC9fiEzBvYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});